server:
  port: 8080
#mybatis数据源配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/db_ms?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver

#mybatis的mapper文件
mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml